### PR TITLE
adds a --format=json option to output the raw axe-core results

### PR DESCRIPTION
**Pull request by jaimeiniesta**
Ref. #14

### CODE REVIEW

**Comment by jaimeiniesta** [comment]
Mmm, hold on a second, this is not producing JSON, it's just returning a JavaScript array/object. Will fix that.

**Comment by jaimeiniesta** [comment]
Ready, we're now returning JSON.

**Comment by jaimeiniesta** [comment]
Not quite yet, sorry. There's still some quotes to remove from the output.

**Comment by jaimeiniesta** [comment]
I've moved the logging logic to each report class, this PR is ready to review @ckundo

**Comment by ckundo** [comment]
@jaimeiniesta hello! Thanks for this. Recently Deque released axe-cli, which might work better for what you're doing. I'm considering deprecating this in favor of their tool (which supports json output by the way). Maybe take a look. https://github.com/dequelabs/axe-cli

**Comment by ckundo** [comment]
@jaimeiniesta this looks good to me.

**Comment by jaimeiniesta** [comment]
@ckundo thanks! I have already tried axe-cli and it's a more direct approach for what I need (JSON output), but I'm still relying on accesslint-cli because it runs fine on Node 4.3, which is what's used in AWS Lambda, while axe-cli requires a more recent version of Node - so axe-cli can't run on AWS Lambda by now.

**Pull request merged**
